@startuml
title Base_Surface

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Base_Surface {
  +dimension: Vec2
  +surface: Surface
  +pos: Vec2
  +rect: Rect
  +overshade: bool
  +create_time: int
  +alpha: float
  -_fade_lasttime: int | None
  ..
  +__init__(dimension: Vec2 = None, pos: Vec2 = Vec2(0, 0), isProportion: bool = False)
  +fade(speed: int = 64)
  +draw(screen: Surface)
  +on_close()
  +time_update()
  +on_click(pos: Vec2, player: Player)
}

@enduml
