@startuml
title BorderFlash

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class BorderFlash {
  +overshade: bool
  +player: Player
  +start_time: int
  +duration: int
  +alpha: int
  ..
  +__init__(player: Player, duration: int = 500)
  +draw(screen: Surface)
  +resize(new_dimension: Vec2)
}

@enduml
