@startuml
title Color

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Color {
  {static} +border: str
  {static} +text: str
  {static} +shadow: str
  {static} +background: str
  {static} +black: str
  {static} +white: str
  {static} +greyed: str
  {static} +correct: str
  {static} +wrong: str
  {static} +buzz_light: str
  {static} +buzz_dark: str
  {static} +timer: str
  {static} +overlay: str
  {static} +transparent: str
  {static} +palette: list[str]
  ..
  {static} +assign_colors(players)
}

@enduml
