@startuml
title End_Surface

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class End_Surface {
  +background: Surface
  +players: list[Player]
  +winner: Player | None
  +start_time: int
  +zoom_scale: float
  +quit_button: Rect
  ..
  +__init__(dimension: Vec2, pos: Vec2)
  +time_update()
  +draw(screen: Surface)
  +on_click(pos: Vec2, player: Player)
}

@enduml
