@startuml
title FloatingText

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class FloatingText {
  +player: Player
  +amount: int
  +color
  +font
  +alpha: float
  +start_time: int
  +duration: int
  +pos: Vec2
  +direction: str
  ..
  +__init__(player: Player, amount: int)
  +update(): bool
  +draw(surface: Surface)
}

@enduml
