@startuml
title Grid_Surface

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Grid_Surface {
  +current_player: Player
  +current_board: Board
  +multiplier: int
  +bot_action: tuple[Player, Vec2, int] | None
  +current_popup: Question_Surface | None
  +current_cell: tuple[int, int] | None
  +overlay_surface: ScoreOverlay | None
  +background: Surface
  +grid_dimension: Vec2
  +grid_area: Rect
  +cell_dimension: Vec2
  +grid: list
  +screen_w: int
  +screen_h: int
  ..
  +__init__(dimension: Vec2, pos: Vec2, start_player: Player, is_double: bool = False)
  -_dimension_init()
  -_background_init()
  -_grid_init()
  -_daily_init()
  +squeeze_text(text: str, font, color, target_rect: Rect, padding: int = 5)
  -_setup_background_and_grid()
  +resize(new_dimension: Vec2)
  -_calculate_cell_pos(row: int, col: int): Vec2
  -_get_rowcol(rpos: Vec2): tuple[int, int]
  +advance_turn(current_player: Player)
  +time_update()
  +on_click(pos: Vec2, player: Player)
  +draw(screen: Surface)
  +on_close()
}

@enduml
