@startuml
title Player

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Player {
  +name: str
  +score: int
  +color
  +bot: bool
  +overlay: ScoreOverlay | None
  +wager: int
  +final_answer: str
  ..
  +__init__(name: str, color, bot: bool)
  +add_score(amount: int)
}

@enduml
