@startuml
title ScoreOverlay

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class ScoreOverlay {
  +font
  +floating_texts: list[FloatingText]
  +grid_surface: Grid_Surface
  ..
  +__init__(grid_surface: Grid_Surface)
  +spawn_floating_text(player: Player, amount: int)
  +get_score_rect(player: Player): Rect
  +resize(new_dimension: Vec2)
  +draw(screen: Surface)
}

@enduml
