@startuml
title StartScreen

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class StartScreen {
  +overshade: bool
  +info_font
  +background: Surface
  ..
  +__init__()
  +resize(new_dimension: Vec2)
  +draw(screen: Surface)
  +on_click(pos: Vec2, player: Player)
  +on_close()
}

@enduml
