@startuml
title Surface_Manager

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Surface_Manager {
  {static} +layers: list<Base_Surface>
  {static} +main_screen: Surface | None
  {static} +pointer_img: Surface
  {static} +sounds: dict
  ..
  {static} +init()
  {static} +add_surface(base_surface: Base_Surface)
  {static} +remove_surface(base_surface: Base_Surface)
  {static} -_get_top_collision(pos: Vec2): tuple[Base_Surface | None, Vec2 | None]
  {static} +click_at(pos: Vec2, player: Player)
  {static} +render()
  +update()
  +resize(new_dimension: tuple[int, int])
  {static} +update()
  {static} +resize(new_dimension: tuple[int, int])
  {static} +play_sound(filename: str, volume: float = 0.5)
}

@enduml
