@startuml
title Transition_Surface

skinparam classAttributeIconSize 0
hide circle
skinparam linetype ortho

class Transition_Surface {
  +mode: str
  +create_time: int
  +image: Surface
  +image_rect: Rect
  ..
  +__init__(mode: str = "jeopardy")
  -_bounce(t: float): int
  +draw(screen: Surface)
  +time_update()
  +on_close()
  +resize(new_dimension: Vec2)
}

@enduml
